In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
!pip install numpy

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#Series
s=pd.Series([1,3,'4',6,8])
s

0    1
1    3
2    4
3    6
4    8
dtype: object

In [ ]:
s=pd.Series([1,3,4.8,6,8])
s

0    1.0
1    3.0
2    4.8
3    6.0
4    8.0
dtype: float64

In [ ]:
s1 = pd.Series([1,2,3,4,5],index = ['a','b','c','d','e'])
s1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
s2 = pd.Series({'a':1,'b':2,'c':3})
s2

a    1
b    2
c    3
dtype: int64

In [ ]:
#DataFrames
s3 = pd.DataFrame([1,2,3,4])
s3

   0
0  1
1  2
2  3
3  4

In [ ]:
s4 = pd.DataFrame([[1,2,3,4],
                   [5,6,7,8]])
s4
#

   0  1  2  3
0  1  2  3  4
1  5  6  7  8

In [ ]:
#converting series to dataframe
d1 = pd.DataFrame(s2)
d1

   0
a  1
b  2
c  3

In [ ]:
d2=pd.DataFrame([[1,2,3],[4,5,6],[3,4,5]],columns=['a','b','c'],index=['x','y','z'])
d2

   a  b  c
x  1  2  3
y  4  5  6
z  3  4  5

In [ ]:
#DataFrame from list of Dictionaries
dic=[{'a':1,'b':2},{'a':5,'b':10,'c':20}]
pd.DataFrame(dic,index=['first','second'])

        a   b     c
first   1   2   NaN
second  5  10  20.0

In [ ]:
#DataFrame Operations
d2

   a  b  c
x  1  2  3
y  4  5  6
z  3  4  5

In [ ]:
print(d2['a'])
print(d2['b'])

x    1
y    4
z    3
Name: a, dtype: int64
x    2
y    5
z    4
Name: b, dtype: int64

In [ ]:
d2['d']=d2['a']*d2['b']
d2['e']=d2['a']+d2['b']
d2

   a  b  c   d  e
x  1  2  3   2  3
y  4  5  6  20  9
z  3  4  5  12  7

In [ ]:
pop = d2.pop('c')
d2

   a  b   d  e
x  1  2   2  3
y  4  5  20  9
z  3  4  12  7

In [ ]:
del d2['d']
d2

   a  b  e
x  1  2  3
y  4  5  9
z  3  4  7

In [ ]:
#insert
d2.insert(1,'newcol',[45,60,70])
d2

   a  newcol  b  e
x  1      45  2  3
y  4      60  5  9
z  3      70  4  7

In [ ]:
d2.insert(1,'newcol2',d2['a'])
d2

   a  newcol2  newcol  b  e
x  1        1      45  2  3
y  4        4      60  5  9
z  3        3      70  4  7

In [ ]:
#Append
d={'a':60,'newcol':70,'b':80}
df11=d2._append(d,ignore_index=True)
df11

    a  newcol2  newcol   b    e
0   1      1.0      45   2  3.0
1   4      4.0      60   5  9.0
2   3      3.0      70   4  7.0
3  60      NaN      70  80  NaN

In [ ]:
#random,randint
import numpy as np
d3=pd.DataFrame({'abc':np.random.randint(2,10,size=(10)),'xyz':np.random.randint(2,10,size=(10)),'cde':np.random.randint(2,10,size=(10))})
d3

   abc  xyz  cde
0    6    2    4
1    6    9    8
2    7    8    5
3    6    9    5
4    4    6    9
5    2    2    2
6    8    3    2
7    3    7    7
8    2    4    3
9    5    6    8

In [ ]:
#info & describe
d3.info()
d3.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   abc     10 non-null     int64
 1   xyz     10 non-null     int64
 2   cde     10 non-null     int64
dtypes: int64(3)
memory usage: 372.0 bytes

             abc        xyz       cde
count  10.000000  10.000000  10.00000
mean    4.900000   5.600000   5.30000
std     2.078995   2.716207   2.58414
min     2.000000   2.000000   2.00000
25%     3.250000   3.250000   3.25000
50%     5.500000   6.000000   5.00000
75%     6.000000   7.750000   7.75000
max     8.000000   9.000000   9.00000

In [ ]:
d3.head()

   abc  xyz  cde
0    6    2    4
1    6    9    8
2    7    8    5
3    6    9    5
4    4    6    9

In [ ]:
d3.tail()

   abc  xyz  cde
5    2    2    2
6    8    3    2
7    3    7    7
8    2    4    3
9    5    6    8

In [ ]:
print(d3.loc[9,'abc'])

5

In [54]:
d3.loc[6:9,['abc','xyz']]

   abc  xyz
6    8    3
7    3    7
8    2    4
9    5    6

In [55]:
d3.loc[[1,2,3],['abc','cde']]

   abc  cde
1    6    8
2    7    5
3    6    5

In [53]:
print(d3.iloc[9,0])

5

In [56]:
d3.iloc[2:6,[0,2]]

   abc  cde
2    7    5
3    6    5
4    4    9
5    2    2

In [57]:
d3.abc.values

array([6, 6, 7, 6, 4, 2, 8, 3, 2, 5])

In [58]:
d3['add']=d3.abc+d3.xyz+d3.cde
d3

   abc  xyz  cde  add
0    6    2    4   12
1    6    9    8   23
2    7    8    5   20
3    6    9    5   20
4    4    6    9   19
5    2    2    2    6
6    8    3    2   13
7    3    7    7   17
8    2    4    3    9
9    5    6    8   19

In [59]:
d3['sub']=d3.abc-d3.xyz-d3.cde
d3

   abc  xyz  cde  add  sub
0    6    2    4   12    0
1    6    9    8   23  -11
2    7    8    5   20   -6
3    6    9    5   20   -8
4    4    6    9   19  -11
5    2    2    2    6   -2
6    8    3    2   13    3
7    3    7    7   17  -11
8    2    4    3    9   -5
9    5    6    8   19   -9