In [54]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [55]:
import pandas as pd
import csv

# Increase the field size limit to handle potentially large fields
csv.field_size_limit(10000000) # Setting a sufficiently large limit

data = pd.read_csv("//content//zomato.csv", delimiter= ',', engine='python', on_bad_lines='skip')
data

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12755,https://www.zomato.com/bangalore/sagar-delicac...,"12, Near Ulsoor Lake, Ulsoor, Bangalore",Sagar Delicacy,Yes,No,3.9/5,87,080 41471383,Ulsoor,Casual Dining,"Handi Biryani, Sandwich","North Indian, Chinese, Fast Food, Street Food",500,"[('Rated 4.0', 'RATED\n Yummy South Indian fo...","['Hara Bhara Kabab [6 Pieces]', 'Baby Corn Man...",Dine-out,Church Street
12756,https://www.zomato.com/bangalore/bar-uno-jw-ma...,"JW Marriott Bengaluru, 24/1, Vittal Mallya Roa...",Bar UNO - JW Marriott Bengaluru,No,No,3.9/5,72,+91 8884944330\r\n080 67188544,Lavelle Road,Lounge,"Cocktails, Pizza",Spanish,"2,500","[('Rated 4.0', 'RATED\n Absofuckinglutely lov...",[],Dine-out,Church Street
12757,https://www.zomato.com/bangalore/saatvikk-brig...,"9, First floor, Curzon Complex, Brigade Road, ...",Saatvikk,No,No,2.8/5,132,+91 8041216902,Brigade Road,Casual Dining,"Masala Papad, Cheese Garlic Naan, Coffee, Corn...","North Indian, South Indian, Continental",650,"[('Rated 3.0', 'RATED\n Food was tasty no dou...",[],Dine-out,Church Street
12758,https://www.zomato.com/bangalore/sidewalk-cafe...,"Nahar's Heritage Hotel, 14, St. Marks Road, Ba...",Sidewalk Cafe - Nahar's Heritage Hotel,No,No,3.9/5,136,+91 9886262756\r\n+91 9900498528,St. Marks Road,Casual Dining,"Pizza, Pasta, Waffles, Sandwich, Apple Pie, Sa...","Italian, Fast Food",800,"[('Rated 5.0', 'RATED\n Absolutely superb pla...",[],Dine-out,Church Street
12759,https://www.zomato.com/bangalore/szechwan-cour...,"The Oberoi, 37-39, MG Road, Bangalore",Szechwan Court - The Oberoi,No,No,4.1/5,168,080 25585858\r\n080 41358202,MG Road,Fine Dining,"Crabmeat Soup, Sesame Chicken, Clear Soup, Pek...",Chinese,"2,500","[('Rated 3.0', 'RATED\n Went to this place on...",[],Dine-out,Church Street

In [56]:
data.info()
data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12760 entries, 0 to 12759
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          12760 non-null  object
 1   address                      12760 non-null  object
 2   name                         12760 non-null  object
 3   online_order                 12760 non-null  object
 4   book_table                   12760 non-null  object
 5   rate                         10946 non-null  object
 6   votes                        12760 non-null  int64
 7   phone                        12503 non-null  object
 8   location                     12758 non-null  object
 9   rest_type                    12704 non-null  object
 10  dish_liked                   5788 non-null   object
 11  cuisines                     12750 non-null  object
 12  approx_cost(for two people)  12726 non-null  object
 13  reviews_list                 12760 non-null  object
 14  menu_item                    12760 non-null  object
 15  listed_in(type)              12760 non-null  object
 16  listed_in(city)              12760 non-null  object
dtypes: int64(1), object(16)
memory usage: 1.7+ MB

              votes
count  12760.000000
mean     269.200627
std      758.236871
min        0.000000
25%        7.000000
50%       41.000000
75%      188.000000
max    16345.000000

In [57]:
data.isnull()
data

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12755,https://www.zomato.com/bangalore/sagar-delicac...,"12, Near Ulsoor Lake, Ulsoor, Bangalore",Sagar Delicacy,Yes,No,3.9/5,87,080 41471383,Ulsoor,Casual Dining,"Handi Biryani, Sandwich","North Indian, Chinese, Fast Food, Street Food",500,"[('Rated 4.0', 'RATED\n Yummy South Indian fo...","['Hara Bhara Kabab [6 Pieces]', 'Baby Corn Man...",Dine-out,Church Street
12756,https://www.zomato.com/bangalore/bar-uno-jw-ma...,"JW Marriott Bengaluru, 24/1, Vittal Mallya Roa...",Bar UNO - JW Marriott Bengaluru,No,No,3.9/5,72,+91 8884944330\r\n080 67188544,Lavelle Road,Lounge,"Cocktails, Pizza",Spanish,"2,500","[('Rated 4.0', 'RATED\n Absofuckinglutely lov...",[],Dine-out,Church Street
12757,https://www.zomato.com/bangalore/saatvikk-brig...,"9, First floor, Curzon Complex, Brigade Road, ...",Saatvikk,No,No,2.8/5,132,+91 8041216902,Brigade Road,Casual Dining,"Masala Papad, Cheese Garlic Naan, Coffee, Corn...","North Indian, South Indian, Continental",650,"[('Rated 3.0', 'RATED\n Food was tasty no dou...",[],Dine-out,Church Street
12758,https://www.zomato.com/bangalore/sidewalk-cafe...,"Nahar's Heritage Hotel, 14, St. Marks Road, Ba...",Sidewalk Cafe - Nahar's Heritage Hotel,No,No,3.9/5,136,+91 9886262756\r\n+91 9900498528,St. Marks Road,Casual Dining,"Pizza, Pasta, Waffles, Sandwich, Apple Pie, Sa...","Italian, Fast Food",800,"[('Rated 5.0', 'RATED\n Absolutely superb pla...",[],Dine-out,Church Street
12759,https://www.zomato.com/bangalore/szechwan-cour...,"The Oberoi, 37-39, MG Road, Bangalore",Szechwan Court - The Oberoi,No,No,4.1/5,168,080 25585858\r\n080 41358202,MG Road,Fine Dining,"Crabmeat Soup, Sesame Chicken, Clear Soup, Pek...",Chinese,"2,500","[('Rated 3.0', 'RATED\n Went to this place on...",[],Dine-out,Church Street

In [58]:
data.isnull().sum()

url                               0
address                           0
name                              0
online_order                      0
book_table                        0
rate                           1814
votes                             0
phone                           257
location                          2
rest_type                        56
dish_liked                     6972
cuisines                         10
approx_cost(for two people)      34
reviews_list                      0
menu_item                         0
listed_in(type)                   0
listed_in(city)                   0
dtype: int64

In [59]:
data['dish_liked']

0        Pasta, Lunch Buffet, Masala Papad, Paneer Laja...
1        Momos, Lunch Buffet, Chocolate Nirvana, Thai G...
2        Churros, Cannelloni, Minestrone Soup, Hot Choc...
3                                              Masala Dosa
4                                      Panipuri, Gol Gappe
                               ...
12755                              Handi Biryani, Sandwich
12756                                     Cocktails, Pizza
12757    Masala Papad, Cheese Garlic Naan, Coffee, Corn...
12758    Pizza, Pasta, Waffles, Sandwich, Apple Pie, Sa...
12759    Crabmeat Soup, Sesame Chicken, Clear Soup, Pek...
Name: dish_liked, Length: 12760, dtype: object

In [60]:
data.dropna(inplace=True)
data

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12755,https://www.zomato.com/bangalore/sagar-delicac...,"12, Near Ulsoor Lake, Ulsoor, Bangalore",Sagar Delicacy,Yes,No,3.9/5,87,080 41471383,Ulsoor,Casual Dining,"Handi Biryani, Sandwich","North Indian, Chinese, Fast Food, Street Food",500,"[('Rated 4.0', 'RATED\n Yummy South Indian fo...","['Hara Bhara Kabab [6 Pieces]', 'Baby Corn Man...",Dine-out,Church Street
12756,https://www.zomato.com/bangalore/bar-uno-jw-ma...,"JW Marriott Bengaluru, 24/1, Vittal Mallya Roa...",Bar UNO - JW Marriott Bengaluru,No,No,3.9/5,72,+91 8884944330\r\n080 67188544,Lavelle Road,Lounge,"Cocktails, Pizza",Spanish,"2,500","[('Rated 4.0', 'RATED\n Absofuckinglutely lov...",[],Dine-out,Church Street
12757,https://www.zomato.com/bangalore/saatvikk-brig...,"9, First floor, Curzon Complex, Brigade Road, ...",Saatvikk,No,No,2.8/5,132,+91 8041216902,Brigade Road,Casual Dining,"Masala Papad, Cheese Garlic Naan, Coffee, Corn...","North Indian, South Indian, Continental",650,"[('Rated 3.0', 'RATED\n Food was tasty no dou...",[],Dine-out,Church Street
12758,https://www.zomato.com/bangalore/sidewalk-cafe...,"Nahar's Heritage Hotel, 14, St. Marks Road, Ba...",Sidewalk Cafe - Nahar's Heritage Hotel,No,No,3.9/5,136,+91 9886262756\r\n+91 9900498528,St. Marks Road,Casual Dining,"Pizza, Pasta, Waffles, Sandwich, Apple Pie, Sa...","Italian, Fast Food",800,"[('Rated 5.0', 'RATED\n Absolutely superb pla...",[],Dine-out,Church Street
12759,https://www.zomato.com/bangalore/szechwan-cour...,"The Oberoi, 37-39, MG Road, Bangalore",Szechwan Court - The Oberoi,No,No,4.1/5,168,080 25585858\r\n080 41358202,MG Road,Fine Dining,"Crabmeat Soup, Sesame Chicken, Clear Soup, Pek...",Chinese,"2,500","[('Rated 3.0', 'RATED\n Went to this place on...",[],Dine-out,Church Street

In [61]:
data.fillna(value='NA')
data

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12755,https://www.zomato.com/bangalore/sagar-delicac...,"12, Near Ulsoor Lake, Ulsoor, Bangalore",Sagar Delicacy,Yes,No,3.9/5,87,080 41471383,Ulsoor,Casual Dining,"Handi Biryani, Sandwich","North Indian, Chinese, Fast Food, Street Food",500,"[('Rated 4.0', 'RATED\n Yummy South Indian fo...","['Hara Bhara Kabab [6 Pieces]', 'Baby Corn Man...",Dine-out,Church Street
12756,https://www.zomato.com/bangalore/bar-uno-jw-ma...,"JW Marriott Bengaluru, 24/1, Vittal Mallya Roa...",Bar UNO - JW Marriott Bengaluru,No,No,3.9/5,72,+91 8884944330\r\n080 67188544,Lavelle Road,Lounge,"Cocktails, Pizza",Spanish,"2,500","[('Rated 4.0', 'RATED\n Absofuckinglutely lov...",[],Dine-out,Church Street
12757,https://www.zomato.com/bangalore/saatvikk-brig...,"9, First floor, Curzon Complex, Brigade Road, ...",Saatvikk,No,No,2.8/5,132,+91 8041216902,Brigade Road,Casual Dining,"Masala Papad, Cheese Garlic Naan, Coffee, Corn...","North Indian, South Indian, Continental",650,"[('Rated 3.0', 'RATED\n Food was tasty no dou...",[],Dine-out,Church Street
12758,https://www.zomato.com/bangalore/sidewalk-cafe...,"Nahar's Heritage Hotel, 14, St. Marks Road, Ba...",Sidewalk Cafe - Nahar's Heritage Hotel,No,No,3.9/5,136,+91 9886262756\r\n+91 9900498528,St. Marks Road,Casual Dining,"Pizza, Pasta, Waffles, Sandwich, Apple Pie, Sa...","Italian, Fast Food",800,"[('Rated 5.0', 'RATED\n Absolutely superb pla...",[],Dine-out,Church Street
12759,https://www.zomato.com/bangalore/szechwan-cour...,"The Oberoi, 37-39, MG Road, Bangalore",Szechwan Court - The Oberoi,No,No,4.1/5,168,080 25585858\r\n080 41358202,MG Road,Fine Dining,"Crabmeat Soup, Sesame Chicken, Clear Soup, Pek...",Chinese,"2,500","[('Rated 3.0', 'RATED\n Went to this place on...",[],Dine-out,Church Street

In [62]:
data ['New_Address']=data['address']+data['location']
data

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city),New_Address
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari,"942, 21st Main Road, 2nd Stage, Banashankari, ..."
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ..."
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari,"1112, Next to KIMS Medical College, 17th Cross..."
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari,"1st Floor, Annakuteera, 3rd Stage, Banashankar..."
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12755,https://www.zomato.com/bangalore/sagar-delicac...,"12, Near Ulsoor Lake, Ulsoor, Bangalore",Sagar Delicacy,Yes,No,3.9/5,87,080 41471383,Ulsoor,Casual Dining,"Handi Biryani, Sandwich","North Indian, Chinese, Fast Food, Street Food",500,"[('Rated 4.0', 'RATED\n Yummy South Indian fo...","['Hara Bhara Kabab [6 Pieces]', 'Baby Corn Man...",Dine-out,Church Street,"12, Near Ulsoor Lake, Ulsoor, BangaloreUlsoor"
12756,https://www.zomato.com/bangalore/bar-uno-jw-ma...,"JW Marriott Bengaluru, 24/1, Vittal Mallya Roa...",Bar UNO - JW Marriott Bengaluru,No,No,3.9/5,72,+91 8884944330\r\n080 67188544,Lavelle Road,Lounge,"Cocktails, Pizza",Spanish,"2,500","[('Rated 4.0', 'RATED\n Absofuckinglutely lov...",[],Dine-out,Church Street,"JW Marriott Bengaluru, 24/1, Vittal Mallya Roa..."
12757,https://www.zomato.com/bangalore/saatvikk-brig...,"9, First floor, Curzon Complex, Brigade Road, ...",Saatvikk,No,No,2.8/5,132,+91 8041216902,Brigade Road,Casual Dining,"Masala Papad, Cheese Garlic Naan, Coffee, Corn...","North Indian, South Indian, Continental",650,"[('Rated 3.0', 'RATED\n Food was tasty no dou...",[],Dine-out,Church Street,"9, First floor, Curzon Complex, Brigade Road, ..."
12758,https://www.zomato.com/bangalore/sidewalk-cafe...,"Nahar's Heritage Hotel, 14, St. Marks Road, Ba...",Sidewalk Cafe - Nahar's Heritage Hotel,No,No,3.9/5,136,+91 9886262756\r\n+91 9900498528,St. Marks Road,Casual Dining,"Pizza, Pasta, Waffles, Sandwich, Apple Pie, Sa...","Italian, Fast Food",800,"[('Rated 5.0', 'RATED\n Absolutely superb pla...",[],Dine-out,Church Street,"Nahar's Heritage Hotel, 14, St. Marks Road, Ba..."
12759,https://www.zomato.com/bangalore/szechwan-cour...,"The Oberoi, 37-39, MG Road, Bangalore",Szechwan Court - The Oberoi,No,No,4.1/5,168,080 25585858\r\n080 41358202,MG Road,Fine Dining,"Crabmeat Soup, Sesame Chicken, Clear Soup, Pek...",Chinese,"2,500","[('Rated 3.0', 'RATED\n Went to this place on...",[],Dine-out,Church Street,"The Oberoi, 37-39, MG Road, BangaloreMG Road"

In [63]:
pop=data.pop('address')
data

,url,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city),New_Address
0,https://www.zomato.com/bangalore/jalsa-banasha...,Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari,"942, 21st Main Road, 2nd Stage, Banashankari, ..."
1,https://www.zomato.com/bangalore/spice-elephan...,Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ..."
2,https://www.zomato.com/SanchurroBangalore?cont...,San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari,"1112, Next to KIMS Medical College, 17th Cross..."
3,https://www.zomato.com/bangalore/addhuri-udupi...,Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari,"1st Floor, Annakuteera, 3rd Stage, Banashankar..."
4,https://www.zomato.com/bangalore/grand-village...,Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12755,https://www.zomato.com/bangalore/sagar-delicac...,Sagar Delicacy,Yes,No,3.9/5,87,080 41471383,Ulsoor,Casual Dining,"Handi Biryani, Sandwich","North Indian, Chinese, Fast Food, Street Food",500,"[('Rated 4.0', 'RATED\n Yummy South Indian fo...","['Hara Bhara Kabab [6 Pieces]', 'Baby Corn Man...",Dine-out,Church Street,"12, Near Ulsoor Lake, Ulsoor, BangaloreUlsoor"
12756,https://www.zomato.com/bangalore/bar-uno-jw-ma...,Bar UNO - JW Marriott Bengaluru,No,No,3.9/5,72,+91 8884944330\r\n080 67188544,Lavelle Road,Lounge,"Cocktails, Pizza",Spanish,"2,500","[('Rated 4.0', 'RATED\n Absofuckinglutely lov...",[],Dine-out,Church Street,"JW Marriott Bengaluru, 24/1, Vittal Mallya Roa..."
12757,https://www.zomato.com/bangalore/saatvikk-brig...,Saatvikk,No,No,2.8/5,132,+91 8041216902,Brigade Road,Casual Dining,"Masala Papad, Cheese Garlic Naan, Coffee, Corn...","North Indian, South Indian, Continental",650,"[('Rated 3.0', 'RATED\n Food was tasty no dou...",[],Dine-out,Church Street,"9, First floor, Curzon Complex, Brigade Road, ..."
12758,https://www.zomato.com/bangalore/sidewalk-cafe...,Sidewalk Cafe - Nahar's Heritage Hotel,No,No,3.9/5,136,+91 9886262756\r\n+91 9900498528,St. Marks Road,Casual Dining,"Pizza, Pasta, Waffles, Sandwich, Apple Pie, Sa...","Italian, Fast Food",800,"[('Rated 5.0', 'RATED\n Absolutely superb pla...",[],Dine-out,Church Street,"Nahar's Heritage Hotel, 14, St. Marks Road, Ba..."
12759,https://www.zomato.com/bangalore/szechwan-cour...,Szechwan Court - The Oberoi,No,No,4.1/5,168,080 25585858\r\n080 41358202,MG Road,Fine Dining,"Crabmeat Soup, Sesame Chicken, Clear Soup, Pek...",Chinese,"2,500","[('Rated 3.0', 'RATED\n Went to this place on...",[],Dine-out,Church Street,"The Oberoi, 37-39, MG Road, BangaloreMG Road"

In [64]:
del data['location']
data

,url,name,online_order,book_table,rate,votes,phone,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city),New_Address
0,https://www.zomato.com/bangalore/jalsa-banasha...,Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari,"942, 21st Main Road, 2nd Stage, Banashankari, ..."
1,https://www.zomato.com/bangalore/spice-elephan...,Spice Elephant,Yes,No,4.1/5,787,080 41714161,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ..."
2,https://www.zomato.com/SanchurroBangalore?cont...,San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari,"1112, Next to KIMS Medical College, 17th Cross..."
3,https://www.zomato.com/bangalore/addhuri-udupi...,Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari,"1st Floor, Annakuteera, 3rd Stage, Banashankar..."
4,https://www.zomato.com/bangalore/grand-village...,Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12755,https://www.zomato.com/bangalore/sagar-delicac...,Sagar Delicacy,Yes,No,3.9/5,87,080 41471383,Casual Dining,"Handi Biryani, Sandwich","North Indian, Chinese, Fast Food, Street Food",500,"[('Rated 4.0', 'RATED\n Yummy South Indian fo...","['Hara Bhara Kabab [6 Pieces]', 'Baby Corn Man...",Dine-out,Church Street,"12, Near Ulsoor Lake, Ulsoor, BangaloreUlsoor"
12756,https://www.zomato.com/bangalore/bar-uno-jw-ma...,Bar UNO - JW Marriott Bengaluru,No,No,3.9/5,72,+91 8884944330\r\n080 67188544,Lounge,"Cocktails, Pizza",Spanish,"2,500","[('Rated 4.0', 'RATED\n Absofuckinglutely lov...",[],Dine-out,Church Street,"JW Marriott Bengaluru, 24/1, Vittal Mallya Roa..."
12757,https://www.zomato.com/bangalore/saatvikk-brig...,Saatvikk,No,No,2.8/5,132,+91 8041216902,Casual Dining,"Masala Papad, Cheese Garlic Naan, Coffee, Corn...","North Indian, South Indian, Continental",650,"[('Rated 3.0', 'RATED\n Food was tasty no dou...",[],Dine-out,Church Street,"9, First floor, Curzon Complex, Brigade Road, ..."
12758,https://www.zomato.com/bangalore/sidewalk-cafe...,Sidewalk Cafe - Nahar's Heritage Hotel,No,No,3.9/5,136,+91 9886262756\r\n+91 9900498528,Casual Dining,"Pizza, Pasta, Waffles, Sandwich, Apple Pie, Sa...","Italian, Fast Food",800,"[('Rated 5.0', 'RATED\n Absolutely superb pla...",[],Dine-out,Church Street,"Nahar's Heritage Hotel, 14, St. Marks Road, Ba..."
12759,https://www.zomato.com/bangalore/szechwan-cour...,Szechwan Court - The Oberoi,No,No,4.1/5,168,080 25585858\r\n080 41358202,Fine Dining,"Crabmeat Soup, Sesame Chicken, Clear Soup, Pek...",Chinese,"2,500","[('Rated 3.0', 'RATED\n Went to this place on...",[],Dine-out,Church Street,"The Oberoi, 37-39, MG Road, BangaloreMG Road"

In [65]:
data.insert(2,'Location',data['New_Address'])
data

,url,name,Location,online_order,book_table,rate,votes,phone,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city),New_Address
0,https://www.zomato.com/bangalore/jalsa-banasha...,Jalsa,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari,"942, 21st Main Road, 2nd Stage, Banashankari, ..."
1,https://www.zomato.com/bangalore/spice-elephan...,Spice Elephant,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Yes,No,4.1/5,787,080 41714161,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ..."
2,https://www.zomato.com/SanchurroBangalore?cont...,San Churro Cafe,"1112, Next to KIMS Medical College, 17th Cross...",Yes,No,3.8/5,918,+91 9663487993,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari,"1112, Next to KIMS Medical College, 17th Cross..."
3,https://www.zomato.com/bangalore/addhuri-udupi...,Addhuri Udupi Bhojana,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",No,No,3.7/5,88,+91 9620009302,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari,"1st Floor, Annakuteera, 3rd Stage, Banashankar..."
4,https://www.zomato.com/bangalore/grand-village...,Grand Village,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12755,https://www.zomato.com/bangalore/sagar-delicac...,Sagar Delicacy,"12, Near Ulsoor Lake, Ulsoor, BangaloreUlsoor",Yes,No,3.9/5,87,080 41471383,Casual Dining,"Handi Biryani, Sandwich","North Indian, Chinese, Fast Food, Street Food",500,"[('Rated 4.0', 'RATED\n Yummy South Indian fo...","['Hara Bhara Kabab [6 Pieces]', 'Baby Corn Man...",Dine-out,Church Street,"12, Near Ulsoor Lake, Ulsoor, BangaloreUlsoor"
12756,https://www.zomato.com/bangalore/bar-uno-jw-ma...,Bar UNO - JW Marriott Bengaluru,"JW Marriott Bengaluru, 24/1, Vittal Mallya Roa...",No,No,3.9/5,72,+91 8884944330\r\n080 67188544,Lounge,"Cocktails, Pizza",Spanish,"2,500","[('Rated 4.0', 'RATED\n Absofuckinglutely lov...",[],Dine-out,Church Street,"JW Marriott Bengaluru, 24/1, Vittal Mallya Roa..."
12757,https://www.zomato.com/bangalore/saatvikk-brig...,Saatvikk,"9, First floor, Curzon Complex, Brigade Road, ...",No,No,2.8/5,132,+91 8041216902,Casual Dining,"Masala Papad, Cheese Garlic Naan, Coffee, Corn...","North Indian, South Indian, Continental",650,"[('Rated 3.0', 'RATED\n Food was tasty no dou...",[],Dine-out,Church Street,"9, First floor, Curzon Complex, Brigade Road, ..."
12758,https://www.zomato.com/bangalore/sidewalk-cafe...,Sidewalk Cafe - Nahar's Heritage Hotel,"Nahar's Heritage Hotel, 14, St. Marks Road, Ba...",No,No,3.9/5,136,+91 9886262756\r\n+91 9900498528,Casual Dining,"Pizza, Pasta, Waffles, Sandwich, Apple Pie, Sa...","Italian, Fast Food",800,"[('Rated 5.0', 'RATED\n Absolutely superb pla...",[],Dine-out,Church Street,"Nahar's Heritage Hotel, 14, St. Marks Road, Ba..."
12759,https://www.zomato.com/bangalore/szechwan-cour...,Szechwan Court - The Oberoi,"The Oberoi, 37-39, MG Road, BangaloreMG Road",No,No,4.1/5,168,080 25585858\r\n080 41358202,Fine Dining,"Crabmeat Soup, Sesame Chicken, Clear Soup, Pek...",Chinese,"2,500","[('Rated 3.0', 'RATED\n Went to this place on...",[],Dine-out,Church Street,"The Oberoi, 37-39, MG Road, BangaloreMG Road"

In [66]:
del data['New_Address']
data

,url,name,Location,online_order,book_table,rate,votes,phone,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,Jalsa,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,Spice Elephant,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Yes,No,4.1/5,787,080 41714161,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,San Churro Cafe,"1112, Next to KIMS Medical College, 17th Cross...",Yes,No,3.8/5,918,+91 9663487993,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,Addhuri Udupi Bhojana,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",No,No,3.7/5,88,+91 9620009302,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,Grand Village,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12755,https://www.zomato.com/bangalore/sagar-delicac...,Sagar Delicacy,"12, Near Ulsoor Lake, Ulsoor, BangaloreUlsoor",Yes,No,3.9/5,87,080 41471383,Casual Dining,"Handi Biryani, Sandwich","North Indian, Chinese, Fast Food, Street Food",500,"[('Rated 4.0', 'RATED\n Yummy South Indian fo...","['Hara Bhara Kabab [6 Pieces]', 'Baby Corn Man...",Dine-out,Church Street
12756,https://www.zomato.com/bangalore/bar-uno-jw-ma...,Bar UNO - JW Marriott Bengaluru,"JW Marriott Bengaluru, 24/1, Vittal Mallya Roa...",No,No,3.9/5,72,+91 8884944330\r\n080 67188544,Lounge,"Cocktails, Pizza",Spanish,"2,500","[('Rated 4.0', 'RATED\n Absofuckinglutely lov...",[],Dine-out,Church Street
12757,https://www.zomato.com/bangalore/saatvikk-brig...,Saatvikk,"9, First floor, Curzon Complex, Brigade Road, ...",No,No,2.8/5,132,+91 8041216902,Casual Dining,"Masala Papad, Cheese Garlic Naan, Coffee, Corn...","North Indian, South Indian, Continental",650,"[('Rated 3.0', 'RATED\n Food was tasty no dou...",[],Dine-out,Church Street
12758,https://www.zomato.com/bangalore/sidewalk-cafe...,Sidewalk Cafe - Nahar's Heritage Hotel,"Nahar's Heritage Hotel, 14, St. Marks Road, Ba...",No,No,3.9/5,136,+91 9886262756\r\n+91 9900498528,Casual Dining,"Pizza, Pasta, Waffles, Sandwich, Apple Pie, Sa...","Italian, Fast Food",800,"[('Rated 5.0', 'RATED\n Absolutely superb pla...",[],Dine-out,Church Street
12759,https://www.zomato.com/bangalore/szechwan-cour...,Szechwan Court - The Oberoi,"The Oberoi, 37-39, MG Road, BangaloreMG Road",No,No,4.1/5,168,080 25585858\r\n080 41358202,Fine Dining,"Crabmeat Soup, Sesame Chicken, Clear Soup, Pek...",Chinese,"2,500","[('Rated 3.0', 'RATED\n Went to this place on...",[],Dine-out,Church Street

In [67]:
print(data.loc[400:500,['dish_liked','Location']])

                                            dish_liked  \
400  Salads, Sandwiches, Pasta, Mocktails, Corn San...
401  Coffee, Thali, Kharabath, Masala Dosa, Idli Va...
402  Veg Jaipuri, Neer Dosa, Kulcha, Pepper Chicken...
403  Pizza, Pasta Alfredo, Brownie, Garlic Bread, S...
404  Mocktails, Tomato Soup, Pasta, Nachos, Chaat, ...
405                  Paratha, Lassi, Manchurian, Thali
406  Rolls, Burgers, Juicy Momos, Chicken Momo, Cho...
407                   Macaroon, Mousse, Caramel Eclair
408  Dahi Papadi Chaat, Papdi Chaat, Bhel Puri, Par...
409                                      Chicken Grill
410  Gulab Jamun, Roti, Masala Papad, Babycorn Manc...
411                           Sugarcane Juice, Popcorn
412   Egg Biryani, Tandoori Chicken, Fish, Rumali Roti
413  Rava Dosa, Roti, Masala Dosa, Kulcha, Sandwich...
414  Masala Poori, Bhel Puri, Panipuri, Chaat, Dahi...
415  Faluda, Mango Lassi, Sweet Lassi, Fruit Salad,...
417                Neer Dosa, Sea Food, Pepper Chicken
418  Ginger Chai, Ginger Tea, Banana Cake, Samosa, ...
419        Masala Dosa, Idli, Filter Coffee, Medu Dosa
420  Pizza, Fries, Anjeer Ice Cream, Sandwiches, Ge...
421     Paratha, Kachori, Tea, Lassi, Samosa, Vada Pav
424             Biryani, Chicken Grill, Butter Chicken
456  Pasta, Lunch Buffet, Masala Papad, Paneer Laja...
457  Veg Buffet, Pasta, Salads, Rasmalai, Chaat, Bi...
460  Mocktails, Peri Fries, Lasagne, Pizza, Chicken...
461            Paneer Tikka, Masala Papad, Garlic Naan
464  Gajar Ka Halwa, Lassi, Jeera Rice, Shahi Panee...
465  Pizza, Pasta, Garlic Bread, Nachos, Penne Alfr...
469  Pav Bhaji, Chaat, Sandwiches, Coffee, Noodles,...
471  Andhra Meal, Mutton Biryani, Chicken Sholay, C...
473                 Fries, Oreo Shake, Pasta Arrabiata
474  Churros, Cannelloni, Minestrone Soup, Hot Choc...
475  Butter Naan, Filter Coffee, Pav Bhaji, Vada, B...
476  Cocktails, Pasta, Paneer Tikka, Mocktails, Whe...
477       Lassi, Panneer Butter Masala, Paratha, Thali
478             Mughlai Paratha, Laccha Paratha, Rolls
480  Panneer Butter Masala, Vada, Curd Rice, Idli, ...
481                 Biryani, Chilli Chicken, Neer Dosa
482  Sandwiches, Pasta, Cobb Salad, Pizza, Burgers,...
483                                            Biryani
484  Masala Dosa, Filter Coffee, Maddur Vada, Curd ...
487  Spring Dosa, Coffee, Spring Roll, Masala Papad...
489  Coffee, Spring Roll, Roti, Panneer Butter Masa...
490  Coffee, Spaghetti, Pancakes, Nachos, Pasta, Sa...
493  Masala Chaach, Tomato Shorba, Gajar Ka Halwa, ...
494  Hot Chocolate Fudge, Vanilla Ice Cream, Fudge ...
495  Dhokla, Jalebi, Badam Milk, Rabri, Rasgulla, R...
497                                     Friendly Staff

                                              Location
400  Near National College, 7th Block, Jayanagar, B...
401  459/30, 30th Cross, 4th Block, Jayanagar, Bang...
402  998/20, Poornima Complex, First Floor, Service...
403  2/2, Pattalamma Gudi Street, Armugam Circle, N...
404  539/49, 9th Cross, Kanakpura Road, 7th Block, ...
405  31, 2nd Cross, 1st Stage, Padmanabh Nagar, Kum...
406  32, 22nd Cross, 22nd Main, 2nd Stage, Near BDA...
407  115, 4th Main, 4th Stage, Thyagarajanagar, Nea...
408  4 & 5, 27th Cross, 4th Block, Jayanagar, Banga...
409  222, 100 Feet Road, Near Kathriguppe Signal, O...
410  101, Manjunatha Complex, Near BDA Complex, 22n...
411  44/1, Bull Temple Road, Basavanagudi, Bangalor...
412  2, Chikkalsandra, Uttarahalli Main Road, Uttar...
413  9A Main Road, 3rd Block, Jayanagar, BangaloreJ...
414  6, 2nd Main, 3rd Cross, Chamrajpet, Basavanagu...
415  196, 8th E Main, 27th Cross, 3rd Block, Suraj ...
417  487, 80 Feet Road, Bank Colony, 1st Stage, Ban...
418  525/2, Opposite Lacasa, 10th Main, 33rd Cross,...
419  162 , Kathreguppe Cross Road, 3rd Stage, Banas...
420  30, Surveyor Street, DVG Road, Basavanagudi, B...
421  46, 80 Feet Road, 3rd Stage, Banashankari, Ban...
424  642, 14th Main, Kumaraswamy Layout, BangaloreK...
456  942, 21st Main Road, 2nd Stage, Banashankari, ...
457  Cosmopolitan Club, Ground Floor, 22nd Cross, 3...
460  941, 3rd FLOOR, 21st Main, 22nd Cross, Banasha...
461  172, Ground Floor, Near Jain College, VV Puram...
464  SM Towers, Near Cosmopolitan Club, 4/3/1 & 3/2...
465  2467, 24th Cross, 2nd Stage, Banashankari, Ban...
469  30th Cross, 8th Main, Near Jain Temple, 4th Bl...
471  The President Hotel, 79/8, Diagonal Road, 3rd ...
473  166/A 2nd Floor, R.V Road, Above DTDC Office, ...
474  1112, Next to KIMS Medical College, 17th Cross...
475  19/49, Near National College, 2nd Main, 31st C...
476     523, 33rd Cross, Jayanagar, BangaloreJayanagar
477  86, Shakthi Arcade, 21st Main, 2nd Stage, Near...
478  Near Dayananda Sagar College, Teachers Colony,...
480  199/1, Ajanaya Bhavana, 100 Feet Ring Road, Ka...
481    266/B, 7th Block, Jayanagar, BangaloreJayanagar
482  Shop 66/1, 4th Block, Near Maiys Hotel, 33rd C...
483  1795, Near Police Station, 13th Main, Kumarasw...
484  42, Vani Vilas Road, Ramakrishna Ashrama Circl...
487  1, Monotype, 2nd Stage, Banashankari, Bangalor...
489  17, Gandhi Bazaar Main Road, Basavanagudi, Ban...
490  6th Block, 3rd Stage, Banashankari, BangaloreB...
493  160, Gandhi Bazar Main Road, Basavanagudi, Ban...
494  808/6-1, 24th A Cross, K.R Road, 2nd Stage, Ba...
495  43, BDA Complex, 2nd Stage, Banashankari, Bang...
497  416, 24th Cross, 9th Main, 2nd Stage, Banashan...

In [68]:
print(data.iloc[0:100,[9,6]])

                                            dish_liked  votes
0    Pasta, Lunch Buffet, Masala Papad, Paneer Laja...    775
1    Momos, Lunch Buffet, Chocolate Nirvana, Thai G...    787
2    Churros, Cannelloni, Minestrone Soup, Hot Choc...    918
3                                          Masala Dosa     88
4                                  Panipuri, Gol Gappe    166
..                                                 ...    ...
201  Neer Dosa, Sea Food, Ghee Rice, Marwai Sukka, ...    242
203  White Pasta, Noodles, Babycorn Manchurian, Piz...    163
204  Masala Dosa, Sandwiches, Coffee, Onion Dosa, R...    191
205                              French Fries, Burgers     32
206  Paratha, Boondi Raita, Roti, Kulfi, Panneer Bu...    247

[100 rows x 2 columns]

In [69]:
data=pd.get_dummies(data['name'],dtype=int)
data

,#L-81 Cafe,#refuel,1000 B.C,100ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ°C,12th Main - Grand Mercure,1441 Pizzeria,154 Breakfast Club,1722 Urban Bistro,1947,1980s Games Cafe,...,Zero Mile Punjab,Zhang's - Chinese Restaurant,Zhangs Classic,Zingron,Zodiac,Zodiac - Fortune Select JP Cosmos Hotel,Zoey's,eat.fit,i-Bar - The Park Bangalore,nu.tree
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12755,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12756,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12757,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12758,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12759,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [70]:
data.drop_duplicates()

,#L-81 Cafe,#refuel,1000 B.C,100ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ°C,12th Main - Grand Mercure,1441 Pizzeria,154 Breakfast Club,1722 Urban Bistro,1947,1980s Games Cafe,...,Zero Mile Punjab,Zhang's - Chinese Restaurant,Zhangs Classic,Zingron,Zodiac,Zodiac - Fortune Select JP Cosmos Hotel,Zoey's,eat.fit,i-Bar - The Park Bangalore,nu.tree
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11966,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11984,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12110,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12231,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12233,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [73]:
import pandas as pd
import csv

# Increase the field size limit to handle potentially large fields
csv.field_size_limit(10000000) # Setting a sufficiently large limit

data = pd.read_csv("//content//zomato.csv", delimiter= ',', engine='python', on_bad_lines='skip')
data

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12755,https://www.zomato.com/bangalore/sagar-delicac...,"12, Near Ulsoor Lake, Ulsoor, Bangalore",Sagar Delicacy,Yes,No,3.9/5,87,080 41471383,Ulsoor,Casual Dining,"Handi Biryani, Sandwich","North Indian, Chinese, Fast Food, Street Food",500,"[('Rated 4.0', 'RATED\n Yummy South Indian fo...","['Hara Bhara Kabab [6 Pieces]', 'Baby Corn Man...",Dine-out,Church Street
12756,https://www.zomato.com/bangalore/bar-uno-jw-ma...,"JW Marriott Bengaluru, 24/1, Vittal Mallya Roa...",Bar UNO - JW Marriott Bengaluru,No,No,3.9/5,72,+91 8884944330\r\n080 67188544,Lavelle Road,Lounge,"Cocktails, Pizza",Spanish,"2,500","[('Rated 4.0', 'RATED\n Absofuckinglutely lov...",[],Dine-out,Church Street
12757,https://www.zomato.com/bangalore/saatvikk-brig...,"9, First floor, Curzon Complex, Brigade Road, ...",Saatvikk,No,No,2.8/5,132,+91 8041216902,Brigade Road,Casual Dining,"Masala Papad, Cheese Garlic Naan, Coffee, Corn...","North Indian, South Indian, Continental",650,"[('Rated 3.0', 'RATED\n Food was tasty no dou...",[],Dine-out,Church Street
12758,https://www.zomato.com/bangalore/sidewalk-cafe...,"Nahar's Heritage Hotel, 14, St. Marks Road, Ba...",Sidewalk Cafe - Nahar's Heritage Hotel,No,No,3.9/5,136,+91 9886262756\r\n+91 9900498528,St. Marks Road,Casual Dining,"Pizza, Pasta, Waffles, Sandwich, Apple Pie, Sa...","Italian, Fast Food",800,"[('Rated 5.0', 'RATED\n Absolutely superb pla...",[],Dine-out,Church Street
12759,https://www.zomato.com/bangalore/szechwan-cour...,"The Oberoi, 37-39, MG Road, Bangalore",Szechwan Court - The Oberoi,No,No,4.1/5,168,080 25585858\r\n080 41358202,MG Road,Fine Dining,"Crabmeat Soup, Sesame Chicken, Clear Soup, Pek...",Chinese,"2,500","[('Rated 3.0', 'RATED\n Went to this place on...",[],Dine-out,Church Street

In [74]:
def add(shravya):
  return shravya+1
data['votes']=data['votes'].apply(add)
data

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,776,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,788,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,919,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,89,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,167,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12755,https://www.zomato.com/bangalore/sagar-delicac...,"12, Near Ulsoor Lake, Ulsoor, Bangalore",Sagar Delicacy,Yes,No,3.9/5,88,080 41471383,Ulsoor,Casual Dining,"Handi Biryani, Sandwich","North Indian, Chinese, Fast Food, Street Food",500,"[('Rated 4.0', 'RATED\n Yummy South Indian fo...","['Hara Bhara Kabab [6 Pieces]', 'Baby Corn Man...",Dine-out,Church Street
12756,https://www.zomato.com/bangalore/bar-uno-jw-ma...,"JW Marriott Bengaluru, 24/1, Vittal Mallya Roa...",Bar UNO - JW Marriott Bengaluru,No,No,3.9/5,73,+91 8884944330\r\n080 67188544,Lavelle Road,Lounge,"Cocktails, Pizza",Spanish,"2,500","[('Rated 4.0', 'RATED\n Absofuckinglutely lov...",[],Dine-out,Church Street
12757,https://www.zomato.com/bangalore/saatvikk-brig...,"9, First floor, Curzon Complex, Brigade Road, ...",Saatvikk,No,No,2.8/5,133,+91 8041216902,Brigade Road,Casual Dining,"Masala Papad, Cheese Garlic Naan, Coffee, Corn...","North Indian, South Indian, Continental",650,"[('Rated 3.0', 'RATED\n Food was tasty no dou...",[],Dine-out,Church Street
12758,https://www.zomato.com/bangalore/sidewalk-cafe...,"Nahar's Heritage Hotel, 14, St. Marks Road, Ba...",Sidewalk Cafe - Nahar's Heritage Hotel,No,No,3.9/5,137,+91 9886262756\r\n+91 9900498528,St. Marks Road,Casual Dining,"Pizza, Pasta, Waffles, Sandwich, Apple Pie, Sa...","Italian, Fast Food",800,"[('Rated 5.0', 'RATED\n Absolutely superb pla...",[],Dine-out,Church Street
12759,https://www.zomato.com/bangalore/szechwan-cour...,"The Oberoi, 37-39, MG Road, Bangalore",Szechwan Court - The Oberoi,No,No,4.1/5,169,080 25585858\r\n080 41358202,MG Road,Fine Dining,"Crabmeat Soup, Sesame Chicken, Clear Soup, Pek...",Chinese,"2,500","[('Rated 3.0', 'RATED\n Went to this place on...",[],Dine-out,Church Street